### ISSUE TITLE
Use OpenXR runtime

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#14]
See https://gitlab.engr.illinois.edu/dev-studio/komodo/komodo_unity/-/issues/107

**Comment by davtamay** [comment]
I added OpenXR plugin into our project, but it is meant for native devices. According to this post: https://forum.unity.com/threads/unitys-plans-for-openxr.993225/

We might already be using OpenXR under the hood:

"No, WebXR is a different API that uses OpenXR under the hood. Unity would have to target WebXR which is a completely separate task than supporting OpenXR natively."

rogueyoshi said: ↑
Unity should consider this though. Why not cover that gaping hole in it's featured AR support when it's trying so hard to push devs to use it?

I'll address this one but ask that we keep the thread focused on OpenXR. We’ve been keeping up with the WebXR spec as it matures, and looking at various ways to address the performance constraints. We don't have immediate plans for WebXR at this point. Right now, our main focus is on releasing support for OpenXR.
