### ISSUE TITLE
Display selected build in VR

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#16]
Previously in https://gitlab.engr.illinois.edu/dev-studio/komodo/komodo_unity/-/issues/119 but there are no comments there.

**Comment by davtamay** [comment]
This is bellow the session name on top left menu

**Comment by parseccentric** [comment]
This looked good UI-wise when I saw it last. I think we noticed functionally that it tells you the default build assigned to a lab, rather than the one you chose when you pressed "Start Now," though. Let me know if you made any changes since then, but I think what has to happen now is that we need to add an additional parameter to the portal's session details called something like "selectedBuild", rename the old parameter to something like "defaultBuild", and then choose to read selectedBuild on the Unity side. If that is the case, then I will make a new portal issue.
