### ISSUE TITLE
Height offset slider does not drag in VR

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#23]
See https://gitlab.engr.illinois.edu/dev-studio/komodo/komodo_unity/-/issues/103 .

@davtamay, I know you recently said height offset was fixed. By that, do you mean that...
* Height offset is working as it was before
or
* Height offset can be dragged and it will update every frame to the correct height while you are holding down the laser? 

I haven't had a chance to try it yet.

**Comment by davtamay** [comment]
Scroll_VR_EventHandler.cs was fixed in the github version to provide continuous dragging when triggering the hand laser on the scroll bar bounds. I also provided a prefab in the project to create custom ones.
