### ISSUE TITLE
Teleport arc could indicate more clearly an invalid selection

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#27]
Previously in https://gitlab.engr.illinois.edu/dev-studio/komodo/komodo_unity/-/issues/124 , but there are no comments there.

**Comment by davtamay** [comment]
An implementation question about this one, should an invalid selection be a change of the arc color (red)? or no arc at all?

**Comment by parseccentric** [comment]
Sorry I have not answered this earlier. My hunch is that red is better, because then the arc still leads your eye out to where the cylinder is.

**Comment by davtamay** [comment]
Hotfix in 701ff22 (Purple when selecting, Red when invalid)
