### ISSUE TITLE
Review client spawn manager

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#28]
Previously in https://gitlab.engr.illinois.edu/dev-studio/komodo/komodo_unity/-/issues/143 , but there are no comments there.

**Comment by davtamay** [comment]
ClientSpawnManager was furthered refactored by placing scene and UI code within their own managers.

**Comment by parseccentric** [comment]
I believe this was in https://github.com/gelic-idealab/komodo-unity/pull/44.
