### ISSUE TITLE
Upgrade to Unity 2019.4 LTS

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#33]
See https://gitlab.engr.illinois.edu/dev-studio/komodo/komodo_unity/-/issues/106 .

**Comment by davtamay** [comment]
- we are at 2020.2 now, I am taking advantage of the Entity package to store the data for the network components (it provides for optimization potential, prepares us to move into using ECS and hopefully to using Unity Tiny once they refine it more). This may affect our ability to regress to earlier versions of unity.
