### ISSUE TITLE
Siccity loader does not load textures properly

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#45]
To reproduce: 
Load a non-Tilt-Brush model that has image textures on it. The model should appear without a texture, like in the case of the Komodo dragon model, or it should be completely invisible, like in the case of models generated with images-to-glbs.glitch.me .

v0.2.0

FireFox with Oculus Runtime and Quest
Chrome with Oculus Runtime
Quest with Oculus Browser

Models:
* [Mood Board](https://s3.us-east-2.amazonaws.com/vrcat-assets/dd130325-336a-4356-91dc-00a76074b025/model.glb)
* [Komodo Dragon](https://s3.us-east-2.amazonaws.com/vrcat-assets/9bc7be11-8784-44a5-a621-0705f0e8e5dc/model.glb)

**Comment by parseccentric** [comment]
![image](https://user-images.githubusercontent.com/8165314/106798468-a0a52c80-6623-11eb-918e-ffd0a9808137.png)
Left: v0.2.0 -- dragon is a plain, white material. Right: v0.1.7 -- dragon has multicolored image texture on it.

**Comment by parseccentric** [comment]
![image](https://user-images.githubusercontent.com/8165314/106798633-da763300-6623-11eb-85cc-6b4e60bedf00.png)
Left: v0.2.0 -- canvases are completely invisible. Right: v0.2.0 -- canvases are visible.

**Comment by parseccentric** [comment]
For the dragon, it creates a material properly:
![image](https://user-images.githubusercontent.com/8165314/106802556-bc5f0180-6628-11eb-84a2-1ea747b5e0e4.png)


But is missing an albedo. I'm not sure if the original model has a metallic gloss map. Edit: yes, it is supposed to have both. It does not use any extensions, and is a completely valid GLTF file.
![image](https://user-images.githubusercontent.com/8165314/106802586-c54fd300-6628-11eb-85f9-3368a90153a7.png)


The mood board is invisible in the editor:
![image](https://user-images.githubusercontent.com/8165314/106802974-4909bf80-6629-11eb-9639-30dad6af6c4b.png)


There is a suspicious error.
![image](https://user-images.githubusercontent.com/8165314/106803019-51fa9100-6629-11eb-846c-f1b14a0171c5.png)


The material itself looks fine, though.
![image](https://user-images.githubusercontent.com/8165314/106803049-5fb01680-6629-11eb-9143-832a453cceea.png)



Aha: the mesh has no triangles. ~I'm not sure why, though. This is a standard cube exported from three.js.~ Edit: instead, the 12 triangles live in the submesh of this mesh. 
![image](https://user-images.githubusercontent.com/8165314/106803432-d4835080-6629-11eb-8b73-4bf7498179dd.png)




If I keep the material the same but change out the MeshFilter to a standard cube, it reveals that the problem for the canvases is a lack of valid mesh rather than a material problem.
![image](https://user-images.githubusercontent.com/8165314/106803874-45c30380-662a-11eb-8a05-549dd4bac0a2.png)

**Comment by parseccentric** [comment]
I think I'm stuck. 

The Siccity docs (paltry as they are, sadly) indicate that static meshes, including submeshes, are supposed to be supported. 

I tried looking up submeshes to understand them better, but the [GLTF 2.0 Specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes) does not even mention them. The explanation is that submeshes can be thought of as the content of the mesh, which is actually an array. So submeshes are elements of the primitive array. At least, according to my understanding of this Microsoft documentation quote:
> Submeshes are defined in the array of primitives on the mesh in the object.
Source: https://docs.microsoft.com/en-us/windows/mixed-reality/distribute/creating-3d-models-for-use-in-the-windows-mixed-reality-home#node-counts-and-submesh-limits

Other folks having related problems:

* https://github.com/Siccity/GLTFUtility/issues/58
* https://github.com/Siccity/GLTFUtility/issues/41

**Comment by davtamay** [comment]
Good information gathered. Can you remember if 0.17 was using Trilib?

**Comment by parseccentric** [comment]
I believe so. 

I am currently trying out swapping Siccity/UnityGLTF with https://github.com/atteneder/glTFast , which interestingly De-Panther WebXR Exporter uses. 

If this works, I will be really excited, because look at this super awesome demo page they have. https://atteneder.github.io/glTFastWebDemo/?#

**Comment by davtamay** [comment]
Cool yes that sounds good, it is supposed to make asset importing faster. I was going to implement it but I got discouraged because I read it lacked some features still such as Animations.

**Comment by davtamay** [comment]
Interesting [recent release](https://github.com/atteneder/glTFast/releases) thought, his importer may fix issues with using big assets. Doing async is the way to go, Siccity offers async but we currently have loading functionality being done in sync which might explain the run time issues we may be experiencing with large assets. I just saw that Siccity does offer async funcionality but is not as straight forward as our current implementation (We have to send a delegate when calling the loader and wait until we get the object back through the callback)

**Comment by parseccentric** [comment]
> Cool yes that sounds good, it is supposed to make asset importing faster. I was going to implement it but I got discouraged because I read it lacked some features still such as Animations.

Yeah, I find this disappointing too. Maybe now we can use multiple loaders -- GLTFast for most cases, and then Siccity for animations.

> Interesting recent release thought, his importer may fix issues with using big assets. Doing async is the way to go, Siccity offers async but we currently have loading functionality being done in sync which might explain the run time issues we may be experiencing with large assets. I just saw that Siccity does offer async funcionality but is not as straight forward as our current implementation (We have to send a delegate when calling the loader and wait until we get the object back through the callback)

Hmm. I am thinking about starting a new Komodo Internal thread to keep info about async-await in one place. I am trying to wrap my head around it, and some users report there's super buggy behavior when using WebGL and WASM.

**Comment by parseccentric** [comment]
Summary of progress in my local branch: 

- AssetImportInitializer now specifies a LoadLocalFile function that accepts a callback in addition to the local filename. 
- TiltBrushAndGLTFastLoader has been created
    - TiltBrush functionality is not changed
    - GLTFast loader will create a gameObject, attach KomodoGLTFAsset component to it, and then call the loader on that component. 
        - The custom component will call the callback we pass in, which will finish the setup.
- Removed log files


This works fine in the editor. 


For some reason, when I go to test it on the dev server, it gives an error about the local filesystem access. 
![image](https://user-images.githubusercontent.com/8165314/107296384-df2d5380-6a36-11eb-9ca5-1e101b43ce96.png)

GLTFast does have its own download handler. Do you think we could integrate that with our existing system?

**Comment by wallacerob** [comment]
@parseccentric any updates for this one? Maybe ok to close now that we have a dev build with glTFast working?
