### ISSUE TITLE
On grab-with-both-hands-to-resize, position of hands relative to the surface of the object should always stay the same

### ISSUE THREAD

**Issue by davtamay** [gelic-idealab/komodo-unity#5]
Here's an illustrative example.  Teaching Tilt Brush: Selection Tool (timestamp 3:31)  The stroke does not jump in location once he activates both grip triggers, and his hands are always touching the same part of the stroke, except for the part at the very end

**Comment by davtamay** [comment]
Resolved by implementing a different double grab strategy that does not have the object readjust itself to the center of the users two hands.

**Comment by parseccentric** [comment]
(video referred above by Shameless Mayhem: https://www.youtube.com/watch?v=EvkhA05O7Nw)
