### ISSUE TITLE
Session 79 Crash on Quest

### ISSUE THREAD

**Issue by davtamay** [gelic-idealab/komodo-unity#6]
I remember this session used to work with Quest using the Trilib loader, with SiccityGLTFLoader it crashes in the end with the "Uncaught Runtime Error"

**Comment by davtamay** [comment]
Used to work with Trilib loader, with SiccityGLTFLoader it crashes in the end of the loading process without error

**Comment by parseccentric** [comment]
Unfortunately, it looks like we did not get around to updating this issue before we moved to a GLTFast loader. I'll reopen this upon request for anyone using Siccity/GLTFUtility with Komodo.
