### ISSUE TITLE
Disable VR-only features and add hints for spectator mode

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#81]
Goals: 

- Disable VR-only features and add hints
- Write manual test descriptions

Details: 

- Disable any tabs & panels that are irrelevant
    - Create menu
- Disable any tools that are irrelevant
    - Height calibration
    - Height adjustment
- Show tips for tools that are only partially working
    - Remind users that visibility & lock buttons are synchronized
    - Remind users that moving and resizing models is only supported in VR for now
- Advanced suggestion
    - Create a debug mode where we can re-enable all tools, tabs, and panels so we can test buttons and tabs in the editor without using a VR headset

(Note: the label "main-branch" just means this is a problem that exists in the main branch.)

**Comment by Barasakar** [comment]
It doesn't seem like there is a way for me to test my code without building the project, uploading it to the server, and testing it on the server. Here is the reason: I disabled the script ```ToggleMenuDisableMode.cs``` and entered play mode; I could still move around and interact with menu. This made me realized that no matter how I change scripts it wouldn't be reflected in Unity play mode. However, I might be totally wrong and don't know what I am doing.
Regardless, I will build my current change and try it on the server.
